### PR TITLE
Fix overlap on mobile view

### PR DESCRIPTION
**Pull request by junsantilla**
Fix overlap between fork-corner and web content on mobile view.

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Do you have the screenshot for before and after? @junsantilla

**Comment by junsantilla** [comment]
before
after

**Comment by junsantilla** [comment]
after
before

**Comment by junsantilla** [comment]
before
after

**Comment by WarenGonzaga** [comment]
Don't touch the @junsantilla main CSS file for fork corner if you intend to make changes on demo please use the style dedicated file not the main fork-corner CSS files it will affect all end user of Fork Corner with this changes by centering their content unintentionally. Submit new PR with changes in style.css not the fork-corner.css I love the changes however you edited the main fork-corner files which will affect entire users.

**Pull request closed without merging**
